example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import submit_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('submit_ajax/', submit_ajax, name='submit_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here


class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')

    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  # melakukan login terlebih dahulu
            response = HttpResponseRedirect(
                reverse("wishlist:show_wishlist"))  # membuat response
            # membuat cookie last_login dan menambahkannya ke dalam response
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response


@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Muhammad Vicky Maulana',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)


@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'nama': 'Muhammad Vicky Maulana',
        'last_login': request.COOKIES['last_login'],
        'logged_in': request.user.is_authenticated,
    }
    return render(request, "wishlist_ajax.html", context)


@login_required(login_url='/wishlist/login/')
def submit_ajax(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')
        BarangWishlist.objects.create(
            nama_barang=nama_barang,
            harga_barang=harga_barang,
            deskripsi=deskripsi,
        )
        return HttpResponseRedirect('/wishlist/ajax/')
    return HttpResponse('Data gagal disimpan')


def show_xml(request):
    # menyimpan hasil query dari seluruh data yang ada pada BarangwishList
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <nav class="navbar navbar-expand-lg navbar-light d-flex justify-content-between" style="background-color: #e3f2fd;">
    <a class="navbar-brand mx-5"> Vicky's Lab </a>
    <a class="btn btn-primary mx-5" href="{% url 'wishlist:login' %}"> Wishlist App </a>
  </nav>
  <div class="d-flex justify-content-center mt-5">
    <h1 class="text-center">Goodbye, world 😥</h1>
  </div>
  
  <!-- <h3>This is example app for Django template</h3> -->
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  <h1>Hello, world!</h1>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<style>
    .gradient-custom {
        /* fallback for old browsers */
        background: #6a11cb;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
    }
</style>
{% endblock meta %}

{% block content %}

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="mb-md-5 mt-md-4 pb-5">
                            <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                            <p class="text-white-50 mb-5">Please enter your login and password!</p>

                            <div class="form-outline form-white mb-4">

                            </div>
        
                            <form method="POST" class="">
                                {% csrf_token %}
                                <table class="d-flex justify-content-center">
                                    <div class="form-outline form-white mb-4">
                                        <label class="form-label">Username</label>
                                        <input type="text" name="username" placeholder="Username" class="form-control">
                                    </div>
                                    
                                    <div class="form-outline form-white mb-4">
                                        <label class="form-label">Password</label>
                                        <input type="password" name="password" placeholder="Password" class="form-control">
                                    </div>

                                    <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>

                                </table>
                            </form>

                            <div class="text-center">
                                {% if messages %}
                                <ul>
                                    {% for message in messages %}
                                        <li>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            </div>
                            
                            
                            <div class="text-center mt-4">
                                Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>
                            </div>
                        </div>
                        
                    </div>
                    
                </div>
                
            </div>
            
        </div>
    </div>
</section>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1 class="text-center">Formulir Registrasi</h1>  

        <form method="POST" class="d-flex justify-content-center">  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light justify-content-between" style="background-color: #e3f2fd;">
    <a class="navbar-brand mx-5"> {{ nama }} </a>
    <div class="d-flex justify-content-end">
        <a class="btn btn-primary" href="{% url 'wishlist:show_wishlist_ajax' %}"> Ajax Version </a>
        <a class="btn btn-danger mx-5" href="{% url 'wishlist:logout' %}"> Logout </a>
    </div>
    
</nav>

<h5 class="text-center mt-5">My Wishlist</h5>

<div class="row justify-content-center mt-4">
    <div class="col-auto">
        <table class="table table-responsive">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Nama Barang</th>
                    <th scope="col">Harga Barang</th>
                    <th scope="col">Deskripsi</th>
                </tr>
            </thead>
            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            {% for barang in list_barang %}
            <tbody>
                <th>{{barang.nama_barang}}</th>
                <th>{{barang.harga_barang}}</th>
                <th>{{barang.deskripsi}}</th>
            </tbody>
            {% endfor %}
        </table>
    </div>
</div>

<h5 class="text-center mt-4">Sesi terakhir login: {{ last_login }}</h5>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
      $("#get-data").click(function(){
        $.get(window.location.href.replace("ajax", "json"), function(data) {
          $("#wishlist-data").empty();
          data.forEach(function(item) {
            $("#wishlist-data").append(
              `<tr>
                <td>${item.fields.nama_barang}</td>
                <td>${item.fields.harga_barang}</td>
                <td>${item.fields.deskripsi}</td>
              </tr>`
            );
          });
        });
      });
    });

    function postAjax() {
      $("form#wishlist-form").submit(function (e) {
            e.preventDefault();
            var actionURL = event.currentTarget.action;
            var formData = $("form#wishlist-form").serialize();
            console.log(formData);
            $.ajax({
                url: actionURL,
                type: "POST",
                data: formData,
                success: (data) => {
                    alert("success!");
                },
                error: (error) => {
                    console.log(error);
                    alert("Error!");
                }
            });
        });
    }

</script>

{% endblock meta %}


{% block content %}

<nav class="navbar navbar-expand-lg navbar-light d-flex justify-content-between" style="background-color: #e3f2fd;">
    <a class="navbar-brand mx-5"> {{ nama }} </a>
    <a class="btn btn-danger mx-5" href="{% url 'wishlist:logout' %}"> Logout </a>
</nav>

<div class="row justify-content-center mt-4">
    <div class="col-auto">
        <table class="table table-responsive">
            <thead class="table-dark">
                <tr>
                    <th scope="col" class="text-center">Nama Barang</th>
                    <th scope="col" class="text-center">Harga Barang</th>
                    <th scope="col" class="text-center">Deskripsi</th>
                </tr>
            </thead>
            <tbody class="text-center" id="wishlist-data">
            </tbody>
        </table>
    </div>
</div>
  
<div class="text-center">
  <button id="get-data" class="btn btn-primary">Get Data</button>
</div>

<div class="d-flex justify-content-center mt-5">
  <form method="POST" action="{% url 'wishlist:submit_ajax' %}" id="wishlist-form">
    {% csrf_token %}
    <input type="text" name="nama_barang" placeholder="Nama Barang" required/>
    <input type="number" name="harga_barang" placeholder="Harga Barang" required/>
    <input type="text" name="deskripsi" placeholder="Deskripsi" required/>
    <input type="submit" value="Tambah" />
  </form>  
</div>

<h5 class="text-center mt-4">Sesi terakhir login: {{ last_login }}</h5>

{% endblock content %}